model_path: "stabilityai/stable-diffusion-xl-base-1.0"
vae_path: "madebyollin/sdxl-vae-fp16-fix"
controlnet_model: "lllyasviel/sd-controlnet-scribble"
control_mode: "sketch"
data_dir: "src/data"
cache_dir: "src/data/cache"
prompt: "A futuristic warrior with glowing armor and a cybernetic arm"
negative_prompt: "blurry, low resolution, distorted"
num_inference_steps: 50
guidance_scale: 7.5